/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A live token source backed by a JS callback. Hand off to
 * [`OpenShellClient::set_oidc_refresher`] before any RPCs run; the SDK
 * proactively refreshes when the token is within 60s of expiry, and
 * coalesces concurrent refreshes into a single callback invocation.
 */
export declare class OidcRefresher {
  /**
   * Create a refresher with an initial token and a JS callback.
   *
   * The callback must return a Promise resolving to
   * `{ accessToken, expiresAt? }`. `expiresAt` is Unix epoch seconds.
   */
  constructor(initialToken: string, initialExpiresAt: number | undefined | null, callback: () => Promise<{ accessToken: string; expiresAt?: number }>)
  /**
   * Snapshot the current token (no refresh check). Mostly useful for
   * tests; in steady-state the SDK calls this internally.
   */
  currentToken(): string
  /**
   * Force a refresh now and return the new access token. Concurrent
   * callers coalesce.
   */
  refresh(): Promise<string>
}

/**
 * The JS-facing client. Cheap to share between async tasks; do not call
 * `connect` per request.
 */
export declare class OpenShellClient {
  /** Open a connection to the gateway described by `options`. */
  static connect(options: ConnectOptions): Promise<OpenShellClient>
  /** Gateway health snapshot. */
  health(): Promise<Health>
  /** Create a new sandbox. */
  createSandbox(spec: SandboxSpec): Promise<SandboxRef>
  /** Fetch a sandbox by name. */
  getSandbox(name: string): Promise<SandboxRef>
  /** List sandboxes. */
  listSandboxes(options?: ListOptions | undefined | null): Promise<Array<SandboxRef>>
  /**
   * Delete a sandbox by name. Returns `true` when the gateway acknowledged
   * the deletion, `false` when it was already absent.
   */
  deleteSandbox(name: string): Promise<boolean>
  /** Poll until the sandbox reaches `ready` or `timeout_secs` elapses. */
  waitReady(name: string, timeoutSecs: number): Promise<SandboxRef>
  /** Poll until the sandbox is gone or `timeout_secs` elapses. */
  waitDeleted(name: string, timeoutSecs: number): Promise<void>
  /** Run a command inside a sandbox; buffers stdout/stderr to the end. */
  exec(name: string, command: Array<string>, options?: ExecOptions | undefined | null): Promise<ExecResult>
}

/**
 * Connection options. Mirrors [`openshell_sdk::ClientConfig`] with
 * JS-friendly field names.
 */
export interface ConnectOptions {
  /** Gateway URL (`http://...` or `https://...`). */
  gateway: string
  /** CA certificate (PEM-encoded). `None` falls back to system roots. */
  caCert?: Buffer
  /** Bearer token for direct OIDC auth. Mutually exclusive with `edge_token`. */
  oidcToken?: string
  /** Cloudflare Access bearer token. Routes through a local WebSocket tunnel. */
  edgeToken?: string
  /** Disable TLS certificate verification (development/debug only). */
  insecureSkipVerify?: boolean
}

/** Options for [`OpenShellClient::exec`]. */
export interface ExecOptions {
  workdir?: string
  environment?: Record<string, string>
  /** Timeout in seconds. `None` lets the gateway choose. */
  timeoutSecs?: number
  /** Optional stdin payload. */
  stdin?: Buffer
}

/** Result of a non-streaming exec call. */
export interface ExecResult {
  exitCode: number
  stdout: Buffer
  stderr: Buffer
}

/** Gateway health snapshot. */
export interface Health {
  /** Coarse status: `"healthy"`, `"degraded"`, `"unhealthy"`, `"unspecified"`. */
  status: string
  version: string
}

/** JS-side refresh callback returning a Promise<{ accessToken, expiresAt? }>. */
export interface JsRefreshedToken {
  accessToken: string
  /**
   * Expiry as Unix epoch seconds. Stored as `f64` because JS numbers
   * can't hold `u64` exactly past 2^53; values are clamped to that range
   * in practice (the year 287396 is fine).
   */
  expiresAt?: number
}

/** Options for [`OpenShellClient::list_sandboxes`]. */
export interface ListOptions {
  limit?: number
  offset?: number
  labelSelector?: string
}

/**
 * Lifecycle phase: `"unspecified"`, `"provisioning"`, `"ready"`, `"error"`,
 * `"deleting"`, `"unknown"`.
 */
export interface SandboxRef {
  id: string
  name: string
  phase: string
  labels: Record<string, string>
  /** Resource version as a string — JS numbers can't safely hold u64. */
  resourceVersion: string
}

/** Caller intent for a new sandbox. */
export interface SandboxSpec {
  name?: string
  image?: string
  labels?: Record<string, string>
  environment?: Record<string, string>
  providers?: Array<string>
  gpu?: boolean
  gpuDevice?: string
}
