// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Aggregated auth metadata for every gRPC method.
//!
//! The per-method tables are generated by `#[rpc_authz]` (see
//! `openshell-server-macros`) and live next to each service's `impl`
//! block. This module merges them and exposes the lookup functions
//! consumed by `authz.rs` (role/scope), `oidc.rs` (unauthenticated
//! check), and `sandbox_methods.rs` (sandbox principal allowlist).

/// Per-method auth metadata emitted by `#[rpc_authz]`.
///
/// Built at compile time and looked up at request-dispatch time.
#[derive(Debug, Clone, Copy)]
pub struct MethodAuth {
    /// Canonical gRPC path (`/package.Service/Method`).
    pub path: &'static str,
    /// Authentication mode for the method.
    pub mode: AuthMode,
    /// Required OIDC scope on the Bearer path. `None` when the method
    /// is `unauthenticated` or `sandbox`-only.
    pub scope: Option<&'static str>,
    /// Required role on the Bearer path. `None` when the method is
    /// `unauthenticated` or `sandbox`-only.
    pub role: Option<Role>,
}

/// How a gRPC method is authenticated.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuthMode {
    /// No authentication required (e.g. health probes).
    Unauthenticated,
    /// Only callable by a `Principal::Sandbox` (gateway-minted sandbox JWT).
    /// See `auth/sandbox_jwt.rs`.
    Sandbox,
    /// Bearer (OIDC) authentication required.
    Bearer,
    /// Either sandbox principal or Bearer; scope and role apply on
    /// the Bearer path only.
    Dual,
}

/// Coarse role mapping. Maps to the configured `admin_role` /
/// `user_role` names at runtime.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    Admin,
    User,
}

/// All per-service auth tables in one flat list.
///
/// Add a new service by appending its module's `AUTH_METADATA` const here.
/// The constant name is fixed by `#[rpc_authz]`; service disambiguation
/// comes from the module path.
const SERVICES: &[&[MethodAuth]] = &[crate::grpc::AUTH_METADATA, crate::inference::AUTH_METADATA];

/// Find the auth metadata for `method`, if any.
#[must_use]
pub fn lookup(method: &str) -> Option<&'static MethodAuth> {
    for table in SERVICES {
        if let Some(entry) = table.iter().find(|m| m.path == method) {
            return Some(entry);
        }
    }
    None
}

/// All registered RPC paths across every service. Used by tests.
#[cfg(test)]
pub fn all_paths() -> impl Iterator<Item = &'static str> {
    SERVICES.iter().flat_map(|s| s.iter()).map(|m| m.path)
}

/// Required Bearer scope for the method, or `None` if scopes don't
/// apply (`unauthenticated`, `sandbox`).
#[must_use]
pub fn required_scope(method: &str) -> Option<&'static str> {
    lookup(method).and_then(|m| m.scope)
}

/// Required role for the method on the Bearer path.
#[must_use]
pub fn required_role(method: &str) -> Option<Role> {
    lookup(method).and_then(|m| m.role)
}

/// `true` if the method bypasses authentication entirely.
///
/// Note: this checks the per-method tables only. The prefix-based
/// bypass for gRPC reflection and health probes is layered on top by
/// `oidc::is_unauthenticated_method`.
#[must_use]
pub fn is_unauthenticated(method: &str) -> bool {
    matches!(
        lookup(method).map(|m| m.mode),
        Some(AuthMode::Unauthenticated)
    )
}

/// `true` if the method is callable by a `Principal::Sandbox`
/// (`sandbox` or `dual` auth mode).
#[must_use]
pub fn is_sandbox_callable(method: &str) -> bool {
    matches!(
        lookup(method).map(|m| m.mode),
        Some(AuthMode::Sandbox | AuthMode::Dual)
    )
}

/// `true` if the method is callable by a `Principal::User` (`bearer` or
/// `dual` auth mode).
///
/// Unknown methods return `true` so [`AuthzPolicy::check`] still gets a
/// chance to evaluate role/scope and apply the `openshell:all` fallback —
/// the exhaustiveness test prevents this branch from ever firing for real
/// RPCs, but it remains as defense-in-depth.
#[must_use]
pub fn is_user_callable(method: &str) -> bool {
    match lookup(method).map(|m| m.mode) {
        Some(AuthMode::Sandbox | AuthMode::Unauthenticated) => false,
        Some(AuthMode::Bearer | AuthMode::Dual) | None => true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;
    use prost_types::FileDescriptorSet;

    /// Every RPC declared in any proto under `proto/` must have an
    /// `#[rpc_auth(...)]` annotation on its handler. This catches:
    /// - new RPCs added to a proto but no annotation on the handler
    /// - typo'd method names in annotations (path mismatch)
    /// - services that were never given an `#[rpc_authz]` impl
    #[test]
    fn every_proto_rpc_has_an_annotation() {
        let set = FileDescriptorSet::decode(openshell_core::FILE_DESCRIPTOR_SET)
            .expect("decode descriptor set");

        let mut missing: Vec<String> = Vec::new();

        for file in &set.file {
            let package = file.package.as_deref().unwrap_or("");
            // Only check services the gateway actually serves. Skip the
            // compute-driver, sandbox supervisor, and test protos because
            // those are not surfaced through the gateway's gRPC server.
            if package != "openshell.v1" && package != "openshell.inference.v1" {
                continue;
            }
            for svc in &file.service {
                let svc_name = svc.name.as_deref().unwrap_or("");
                for method in &svc.method {
                    let method_name = method.name.as_deref().unwrap_or("");
                    let path = format!("/{package}.{svc_name}/{method_name}");
                    if lookup(&path).is_none() {
                        missing.push(path);
                    }
                }
            }
        }

        assert!(
            missing.is_empty(),
            "RPC methods missing #[rpc_auth] annotation: {missing:?}"
        );
    }

    /// Every annotated path must exist as a real RPC in some proto. This
    /// catches stale annotations after an RPC is removed or renamed.
    #[test]
    fn every_annotated_path_matches_a_real_rpc() {
        let set = FileDescriptorSet::decode(openshell_core::FILE_DESCRIPTOR_SET)
            .expect("decode descriptor set");

        let mut proto_paths: Vec<String> = Vec::new();
        for file in &set.file {
            let package = file.package.as_deref().unwrap_or("");
            for svc in &file.service {
                let svc_name = svc.name.as_deref().unwrap_or("");
                for method in &svc.method {
                    let method_name = method.name.as_deref().unwrap_or("");
                    proto_paths.push(format!("/{package}.{svc_name}/{method_name}"));
                }
            }
        }

        let mut stale: Vec<&'static str> = Vec::new();
        for path in all_paths() {
            if !proto_paths.iter().any(|p| p == path) {
                stale.push(path);
            }
        }

        assert!(
            stale.is_empty(),
            "annotated paths that don't match any real proto RPC: {stale:?}"
        );
    }

    /// Sanity check: no path appears in more than one service table.
    #[test]
    fn no_duplicate_paths_across_services() {
        let mut seen: Vec<&'static str> = Vec::new();
        for path in all_paths() {
            assert!(
                !seen.contains(&path),
                "duplicate path across tables: {path}"
            );
            seen.push(path);
        }
    }

    /// User principals must be rejected for `sandbox` and `unauthenticated`
    /// methods; the auth-mode check at the router enforces this regardless
    /// of role/scope, closing the gap where a token with `openshell:all`
    /// could otherwise reach sandbox-only handlers.
    #[test]
    fn user_callable_matches_auth_mode() {
        // Bearer
        assert!(is_user_callable("/openshell.v1.OpenShell/ListSandboxes"));
        // Dual
        assert!(is_user_callable("/openshell.v1.OpenShell/GetSandboxConfig"));
        // Sandbox-only
        assert!(!is_user_callable(
            "/openshell.v1.OpenShell/ReportPolicyStatus"
        ));
        assert!(!is_user_callable("/openshell.v1.OpenShell/PushSandboxLogs"));
        assert!(!is_user_callable(
            "/openshell.v1.OpenShell/GetSandboxProviderEnvironment"
        ));
        assert!(!is_user_callable(
            "/openshell.v1.OpenShell/SubmitPolicyAnalysis"
        ));
        assert!(!is_user_callable(
            "/openshell.v1.OpenShell/ConnectSupervisor"
        ));
        assert!(!is_user_callable("/openshell.v1.OpenShell/RelayStream"));
        assert!(!is_user_callable(
            "/openshell.inference.v1.Inference/GetInferenceBundle"
        ));
        // Unauthenticated methods are not "user callable" — they're
        // intercepted before principal evaluation.
        assert!(!is_user_callable("/openshell.v1.OpenShell/Health"));
        // Unknown method falls through to AuthzPolicy::check.
        assert!(is_user_callable("/openshell.v1.OpenShell/FutureMethod"));
    }
}
